{
    "type": "bundle",
    "id": "bundle--e35e5f78-fd03-4f36-8a73-57cfed93321e",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--02a66c70-bab2-4eb9-af58-d3ecab67dc78",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-17T00:22:47.562628Z",
            "modified": "2025-04-17T00:22:47.562628Z",
            "name": "CVE-2025-22063",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nnetlabel: Fix NULL pointer exception caused by CALIPSO on IPv4 sockets\n\nWhen calling netlbl_conn_setattr(), addr->sa_family is used\nto determine the function behavior. If sk is an IPv4 socket,\nbut the connect function is called with an IPv6 address,\nthe function calipso_sock_setattr() is triggered.\nInside this function, the following code is executed:\n\nsk_fullsock(__sk) ? inet_sk(__sk)->pinet6 : NULL;\n\nSince sk is an IPv4 socket, pinet6 is NULL, leading to a\nnull pointer dereference.\n\nThis patch fixes the issue by checking if inet6_sk(sk)\nreturns a NULL pointer before accessing pinet6.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-22063"
                }
            ]
        }
    ]
}