{
    "type": "bundle",
    "id": "bundle--3506eeca-1d38-45f5-8e5d-b202d8ae6e51",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--6882af5a-8355-4eee-bf3b-4197de66a34e",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-05-26T00:25:03.546037Z",
            "modified": "2025-05-26T00:25:03.546037Z",
            "name": "CVE-2025-5151",
            "description": "A vulnerability classified as critical has been found in defog-ai introspect up to 0.1.4. This affects the function execute_analysis_code_safely of the file introspect/backend/tools/analysis_tools.py. The manipulation of the argument code leads to code injection. It is possible to launch the attack on the local host. The exploit has been disclosed to the public and may be used. The patch is named 502. It is recommended to apply a patch to fix this issue. The code maintainer explains, that \"[they] have added some workarounds to address this in #502, but will not be implementing a full fix. This is because this repo is meant to be run in a docker environment, which will significantly mitigate potential security risks. Having said that, we have added a SECURITY section in our README to make this clearer to users.\"",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-5151"
                }
            ]
        }
    ]
}