{
    "type": "bundle",
    "id": "bundle--39af3fb5-d79b-45d5-b8d3-0bf4c4b49ec8",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--8211528c-ec09-4f68-8417-303e92c38843",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-09T00:22:48.411552Z",
            "modified": "2025-04-09T00:22:48.411552Z",
            "name": "CVE-2025-32414",
            "description": "In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds memory access can occur in the Python API (Python bindings) because of an incorrect return value. This occurs in xmlPythonFileRead and xmlPythonFileReadRaw because of a difference between bytes and characters.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32414"
                }
            ]
        }
    ]
}